pylint:
  disable:
    - too-many-arguments
    - too-many-positional-arguments
    - too-many-locals
    - import-outside-toplevel
    - wrong-import-position

pycodestyle:
  ignore:
    - E704 # Conflict with ruff formatting