start_date: 2020-02-06
end_date: 2020-02-07

checkpoint_path: /lustre/storeB/project/nwp/aifs/havardhh/bris-inference/inference-anemoi-by_time-epoch_075-step_149656.ckpt

leadtimes: 12 
timestep: 6h
frequency: 6h

dateset:
  dataset: ${hardware.paths.data}${hardware.files.global_dataset}
  start: ${start_date}
  end: ${end_date}


dataloader:
  batch_size: 1
  prefetch_factor: 2
  num_workers: 1
  pin_memory: True

  read_group_size: ${run_options.num_gpus_per_model}

  predict:
    dataset: ${dataset}
    start: ${start_date}
    end: ${end_date}
    frequency: ${frequency}
   

  datamodule:
    _target_: anemoi.training.data.dataset.NativeGridDataset #anemoi.training.data.dataset.ZipDataset
    _convert_: all

hardware:
  paths:
    data: /lustre/storeB/project/nwp/aifs/datasets/
  files:
    lam_dataset: name_of_dataset 
    global_dataset: aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6.zarr
    dataset_obs: name_of_dataset

run_options:
    num_gpus_per_node: 1
    num_gpus_per_model: 1
    num_nodes: 1

model:
  _target_: bris.model.BrisPredictor
  _convert_: all


checkpoints:
  - my_interpolator:
    type: interpolator
    path: interpolator.ckpt
  - my_forecaster:
    type: forecaster
    path: forecast.ckpt

routing:
  - decoder_index: 0
    domain: 0
    outputs:
      - netcdf:
          filename_pattern: pred_%Y%m%dT%HZ.nc
          variables: [2t, mslp]
  - decoder_index: 0
    domain: 1
    outputs:
      - verif:
          filename: global/2t/%R.nc   # global/2t/legendary_gnome.nc
          variable: 2t
          thresholds: [0, 10, 20]
          quantile_levels: [0.1, 0.9]
          obs:
            - netcdf:
                path: 2t.nc
      - verif:
          filename: global/mslp/%R.nc   # global/2t/legendary_gnome.nc
          variable: mslp
          thresholds: [970, 1000, 1020]
          quantile_levels: [0.1, 0.9]
          obs:
            - netcdf:
                path: mslp.nc

  - decoder_index: 1
    domain: 0
    outputs:
      - netcdf:
          filename_pattern: netatmo_%Y%m%dT%HZ.nc
