defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_
  
start_date: 2023-05-31T18:00:00
end_date: 2023-06-01T12:00:00 #2024-06-01T01:00:00

checkpoint_path: /pfs/lustrep4/scratch/project_465001383/aifs/experiments/reference/o96_pretrain/checkpoint/3fb85b72ba9647d5ae4fe86ce1b5a885/inference-last.ckpt

leadtimes: 12
timestep: 6h
frequency: 6h

deterministic: True

global_dataset: ${hardware.paths.data}${hardware.files.global_dataset}

# If the user wants to release GPU cache and memory
# This option releases unused cached/memory used by torch
release_cache: False

dataloader:
  batch_size: 1
  prefetch_factor: 2
  num_workers: 1
  pin_memory: True

  read_group_size: 1 #Do not change this, not implemented properly

  predict:
    dataset: ${global_dataset}
    drop: ['cp', 'u_600', 'v_600', 'z_600', 't_600', 'q_600', 'w_600', 'longitude', 'latitude']
    start: ${start_date}
    end: ${end_date}
    frequency: ${frequency}
    reorder: ${reorder}

  datamodule:
    _target_: bris.data.dataset.NativeGridDataset #anemoi.training.data.dataset.ZipDataset
    _convert_: all

hardware:
  paths:
    data: /pfs/lustrep4//scratch/project_465001383/aifs/dataset/ERA5/
    workdir: /pfs/lustrep4//scratch/project_465001383/haugenha/anemoi-training-ref-updated/run-anemoi/lumi/workdir/
  files:
    global_dataset: aifs-od-an-oper-0001-mars-n320-2023-2024-6h-v2.zarr

  num_gpus_per_node: 8
  num_gpus_per_model: 8
  num_nodes: 1

model:
  _target_: bris.model.BrisPredictor
  _convert_: all


checkpoints:
  - my_interpolator:
    type: interpolator
    path: interpolator.ckpt
  - my_forecaster:
    type: forecaster
    path: forecast.ckpt

routing:
  - decoder_index: 0
    domain: 0
    outputs:
      - netcdf:
          filename_pattern: /pfs/lustrep4/scratch/project_465001383/haugenha/anemoi-training-ref-updated/run-anemoi/lumi/predictions/n320_pred_%Y%m%dT%HZ.nc
          variables: [2t, msl]
      - verif:
          filename: /pfs/lustrep4/scratch/project_465001383/haugenha/anemoi-training-ref-updated/run-anemoi/lumi/verif/2t/n320_at_ref.nc
          variable: 2t
          units: degC
          obs_sources:
            - verif:
                filename: /pfs/lustrep4/scratch/project_465001383/aifs/old_project_misc/verification/202306_202405/t2m/AIFS_legendary_gnome_roll4.nc
#      - verif: 
#          filename_pattern: verif/mslp/n320_at_ref.nc
#          variable: mslp
#          obs:
#            - netcdf:
#                path: /pfs/lustrep4/scratch/project_465001383/aifs/old_project_misc/verification/202306_202405/mslp/AIFS_legendary_gnome_roll4.nc      

  
reorder: ['10u',
 '10v',
 '2d',
 '2t',
 'cos_julian_day',  
 'cos_latitude',
 'cos_local_time',
 'cos_longitude',
 'insolation',
 'lsm',
 'msl',
 'q_100',
 'q_1000',
 'q_150',
 'q_200',
 'q_250',
 'q_300',
 'q_400',
 'q_50',
 'q_500',
 'q_700',
 'q_850',
 'q_925',
 'sin_julian_day',
 'sin_latitude',
 'sin_local_time',
 'sin_longitude',
 'skt',
 'sp',
 't_100',
 't_1000',
 't_150',
 't_200',
 't_250',
 't_300',
 't_400',
 't_50',
 't_500',
 't_700',
 't_850',
 't_925',
 'tcw',
 'tp',
 'u_100',
 'u_1000',
 'u_150',
 'u_200',
 'u_250',
 'u_300',
 'u_400',
 'u_50',
 'u_500',
 'u_700',
 'u_850',
 'u_925',
 'v_100',
 'v_1000',
 'v_150',
 'v_200',
 'v_250',
 'v_300',
 'v_400',
 'v_50',
 'v_500',
 'v_700',
 'v_850',
 'v_925',
 'w_100',
 'w_1000',
 'w_150',
 'w_200',
 'w_250',
 'w_300',
 'w_400',
 'w_50',
 'w_500',
 'w_700',
 'w_850',
 'w_925',
 'z',
 'z_100',
 'z_1000',
 'z_150',
 'z_200',
 'z_250',
 'z_300',
 'z_400',
 'z_50',
 'z_500',
 'z_700',
 'z_850',
 'z_925']
