# run_name: test
start_date: 2022-01-01T00:00:00
end_date: 2022-12-31T06:00:00

checkpoint_path: ./inference-last.ckpt

dataset: ../../train/tmp/bris_random_data.zarr
workdir: /tmp/

leadtimes: 2
frequency: 6h

dataloader:
  datamodule:
    _target_: bris.data.dataset.NativeGridDataset
    _convert_: all

hardware:
  num_gpus_per_node: 1
  num_gpus_per_model: 1
  num_nodes: 1

release_cache: False

model:
  _target_: bris.model.BrisPredictor
  _convert_: all

routing:
  - decoder_index: 0
    domain_index: 0
    domain: 0
    outputs:
      - netcdf:
          filename_pattern: test_pred_%Y%m%dT%HZ.nc
          variables: [2t, 2d]
