# Minimal config for running inference on CPU. See https://github.com/metno/bris-inference/wiki/Tests

start_date: 2022-01-01T00:00:00
end_date: 2022-01-02T00:00:00

checkpoints:
  forecaster:
    checkpoint_path: ./inference-multi.ckpt
    leadtimes: 2

dataset_data: 
  cutout:
    - dataset: PATH_TO_LAM_DATASET
    - dataset: ./bris_random_data.zarr
  min_distance_km: 0
  adjust: all

dataset_obs:
  dataset: PATH_TO_OBS_DATASET

dataset:
  zip:
    - dataset: ${dataset_data}
    - dataset: ${dataset_obs}
  adjust: ["start", "end"]

frequency: 6h
workdir: /tmp/

dataloader:
  datamodule:
    _target_: bris.data.dataset.ZipDataset
    _convert_: all

hardware:
  num_gpus_per_node: 1
  num_gpus_per_model: 1
  num_nodes: 1

model:
  _target_: bris.model.MultiEncDecPredictor
  _convert_: all

routing:
  # Outputs LAM part of stretched grid
  - decoder_index: 0
    domain_index: 0
    outputs:
      # Forecasts
      - netcdf:
          filename_pattern: ./pred_%Y%m%dT%HZ.nc
          variables: [2t, msl]
          extra_variables: [ws] #Compute wind speed from 10u and 10v
  # Outputs decoder 1
  - decoder_index: 1
    domain_index: 0
    outputs: 
      - netcdf:
          filename_pattern: ./pred_dec1_%Y%m%dT%HZ.nc
          variables: [10fg]
